var k=Object.create;var p=Object.defineProperty;var I=Object.getOwnPropertyDescriptor;var D=Object.getOwnPropertyNames;var B=Object.getPrototypeOf,S=Object.prototype.hasOwnProperty;var L=t=>p(t,"__esModule",{value:!0});var R=(t,e,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of D(e))!S.call(t,r)&&r!=="default"&&p(t,r,{get:()=>e[r],enumerable:!(n=I(e,r))||n.enumerable});return t},u=t=>R(L(p(t!=null?k(B(t)):{},"default",t&&t.__esModule&&"default"in t?{get:()=>t.default,enumerable:!0}:{value:t,enumerable:!0})),t);var U=require("crypto"),K=require("fs"),y={computeHash:function(t){return U.createHash("sha256").update(t).digest("base64")},generateUUID:function(t){return"xxxxxxxx-xxxx-4xxxx-xxx-x".replace(/[xy]/g,function(e){var n=Math.random()*16|0,r=e=="x"?n:n&3|8;return r.toString(16)})},filter:function(t,e,n){if(!e.originalname.match(/\.(jpg|JPG|jpeg|JPEG|png|PNG)$/))return t.fileValidationError="Only image files are allowed",n(new Error("Only image files are allowed"),!1);n(null,!0)},getExt:function(t){var e=t.lastIndexOf(".");return e<0?"":t.substr(e)},replaceValues:function(t,e){var t=t.replace(/\[\w*\]/g,function(n,r){return e[n.slice(1,-1)]||n});return t},getFileStream:async function(t){let e=K.createReadStream(t);return await new Promise(function(a,o){e.on("data",d=>a(d.toString())),e.on("error",o)})}};var x=u(require("dotenv"));var g=u(require("sqlite3"));g.default.verbose();var m=class{constructor(e){this._db=new g.default.Database(e),this._db.run("PRAGMA journal_mode = WAL")}run(e,...n){return new Promise((r,a)=>{this._db.run(e,...n,function(o){o?a(o):r(this)})})}get(e,...n){return new Promise((r,a)=>{this._db.get(e,...n,(o,d)=>{o?a(o):r(d)})})}all(e,...n){return new Promise((r,a)=>{this._db.all(e,...n,(o,d)=>{o?a(o):r(d)})})}exec(e,...n){return new Promise((r,a)=>{this._db.exec(e,o=>{o?a(o):r(this)})})}};var l=u(require("express")),w=u(require("cookie-parser")),c=u(require("firebase-admin"));var N="service_account",T="partyshare-47d15",C="e25d712d9968cb22e26c6e479eab353491fd2f44",P=`-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCrEnS10v+DHpno
sbEby4fWlgcjUNFhLkdy+MC/0tEL4lQSIwxVePFWL0ZBpwb+trfnZ7fn2khe9DAx
13bFHVMhKR2Lbgny0e/Ea97NRRmutGdBA33KSKEYjRR4MfGfe3/Cgu6K4dGf8+Lc
sKQ8LByA64UbmnKyDDM2DLG2WtH3+uJ8ALdpDbA2w0NQ3pi3YDdI207EZFJOJVpD
CE/L8qSkqjyP8VWAUstj3H+B2j/Ea5zH8RKtQIzPrwBewdn8PJU1QuKuN700anXh
VqzUJwzEjQamMrx+38h8Q6XBxUw357bUuC389JCiquM0VCnbVfdyEwmD+0eUZ3nl
Ku4MdRRfAgMBAAECggEACCACRw3UcOfSgN4fqVBLYq0RfbiS7pNXdWXMfHqIzzsF
VISG9hrzwMInYMA2xtZAJHolSUUcIYEQ4O0jiPfRlkZGTvRU/fbBSopNCgwkIiC+
CV/JvlfLaZ0ZwckCztj7bRjxjMsY57NFAnJT+pT7GEHCEAOP5augAGCDTZlBVmO8
zjPrHQIBrJDaArbylayhb29XoW25oMsaDGOp1Hlx2Fq3wK7txtgIaD7wSlZtsQB6
FUFB03+kiY9TNTpwp1cbxriTtRgu9RKvyQ0Rvk0TGyUdc0brrHnq2U4ot1VJFj1e
n1WT9iHR4Ovx1qC3Al8MPnBrZ+PraVmN5T0CawdsEQKBgQDipCVTBv0OpkS1E8XI
f+KviQueU893NZUruLJAkHFMJYu6dn//pIxGRw4chVwmWIuS2ZhHsztjW2giznEO
92WE8oFAneb9THQDbVwFfOfuY4GdEULoUrNLhFKK1dfise2GVmp3UgQhENcSwoZR
/Z6s9yaDXNK75taVR055SNObLQKBgQDBO4hhnsduoqeTX52dHn9psnqBfzgbUFHh
fdvTdOqzv++6yaoL22hGQTZMuul0Gg4ryHV9VJZ1L0/1epO/9hxGxom58RJLWCxw
SAuH3ZEjS7KYGZgh+IDDGtcdNhykENLOPEWoG1uukBZerjxa3+eLmvHa8vYMzqiW
MySV4NA1OwKBgQDNJt5uUIYii5jn/DTtL+3HDRuKPr0uYD9eKzqXPOiBj/7yUy+7
/XvIZas9X+4w+7ejvvmb9X6NioEx+ILYlFK9zDH5hrU/lcPyEjzY7t6WqFX8ElLp
L2sCsY1yBO39Uyf5kSGgTopUUAUPAyxI7XWDhdjD0fMjiWm2CKzdFnINJQKBgBL9
r9ywRzd3YvLX/dyYR7tyoBmkEDaXAUUhIn64yexam8wGz+CUcr4c4KJP6GvRt7zT
2cA0lQj1Wm1s26KNJKBMGPMeX0bqZouuePukagRHB0ltkoccLkN+ms+zJsN1J9K/
F7V64trYLGqnwyTHRrFwy/5RzJ7bnLQOWLUmQDBLAoGBALPU5afAQEacP1C8KbVM
J9yDEFpHudwgC8c6MnCK0IIpaS4IA+r8f74q/QswyeANyYX9FggdAp+SM1aDOAcQ
fY0+gOptWoB7NuGfk/rhs6ezo8ivLtXWDKzA44DS0K9NNcf1a+ysP6I0mVws5mA8
QEoYzPmkP+BNjhnXqBg5ykMx
-----END PRIVATE KEY-----
`,G="firebase-adminsdk-dx0dk@partyshare-47d15.iam.gserviceaccount.com",j="115450043492170133553",M="https://accounts.google.com/o/oauth2/auth",O="https://oauth2.googleapis.com/token",Q="https://www.googleapis.com/oauth2/v1/certs",V="https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-dx0dk%40partyshare-47d15.iam.gserviceaccount.com",f={type:N,project_id:T,private_key_id:C,private_key:P,client_email:G,client_id:j,auth_uri:M,token_uri:O,auth_provider_x509_cert_url:Q,client_x509_cert_url:V};var A=u(require("stripe"));x.default.config();var v="http://partyshare.ca",h=new m("database/partyshare.db");async function _(){h.exec("CREATE TABLE IF NOT EXISTS accounts ( id varchar(25) PRIMARY KEY, name varchar(100), email varchar(80), authID varchar(28), location varchar(250) ) "),h.exec("CREATE TABLE IF NOT EXISTS products ( name varchar(75), id varchar(25), accountID varchar(25), imageURL varchar(55), category varchar(12), desc varchar(250), info varchar(200), quantity int, price int, deposit int )")}_();var s=(0,l.default)();s.use(l.default.json());s.use(l.default.urlencoded({extended:!0}));s.use((0,w.default)());c.default.initializeApp({credential:c.default.credential.cert(f),storageBucket:process.env.BUCKET_URL});var X=c.default.firestore(),E=new A.default(process.env.StripeSK,{apiVersion:"2020-08-27"});s.set("view engine","ejs");s.use("/views",l.default.static("views"));async function b(t,e,n){let r=60*60*24*e*1e3,a=await c.default.auth().createSessionCookie(t,{expiresIn:r}),o={maxAge:r};n.cookie("session",a,o)}s.get("/",async(t,e)=>{e.render("homepage/index",{acc:t.cookies.session})});s.get("/vendor-login",async(t,e)=>{e.render("vendor-login/index",{acc:t.cookies.session})});s.get("/accounts/create",async(t,e)=>{let n=y.computeHash(Math.random().toString()).replace("/","|"),r=await E.accounts.create({type:"express",country:"CA",business_type:"individual"}),a=await E.accountLinks.create({account:r.id,refresh_url:`${v}/accounts/create`,return_url:`${v}/accounts/create/${n}`,type:"account_onboarding"});e.cookie("stripeID",r.id),e.redirect(a.url)});s.get("/accounts/create/:hash",async(t,e)=>{e.render("create-account/index")});s.post("/accounts/login",async(t,e)=>{let n=t.body.idToken,r=(await c.default.auth().verifyIdToken(n)).uid;await b(n,14,e),e.end(JSON.stringify({status:"success"}))});s.post("/accounts/create",async(t,e)=>{let n=t.body.idToken,r=(await c.default.auth().verifyIdToken(n)).uid;await b(n,14,e);let a={id:t.cookies.stripeID,name:t.body.name,email:t.body.email,authID:r,location:t.body.location};await h.run("INSERT INTO accounts VALUES (?, ?, ?, ?, ?);",...Object.values(a)),e.end(JSON.stringify({status:"completed"}))});s.get("/verify",async(t,e)=>{let n=t.cookies.session,r=await c.default.auth().verifySessionCookie(n,!1);console.log(r),e.send("complete")});s.get("/logout",async(t,e)=>{e.clearCookie("session"),e.redirect("/")});s.listen(80,()=>{console.log("Server running..."),console.log("")});
//# sourceMappingURL=index.js.map
